Added diagnostic setting support
Azure/terraform-azurerm-openai pull request #14
Opened 2023-06-06 15:32 UTC by paolosalvatori

## Describe your changes
I added the azurerm_monitor_diagnostic_setting resource in the `diagnosticsetting.tf` file to let users define one or more diagnostic settings for the Azure OpenAI resource. Likewise, I extended the `variables.tf` file to include a map to let users define one or more diagnostic settings.

I can extend the tests under the `examples` folder to create a Log Analytics, storage account, and eventually Event Hub and configure one or more diagnostic settings for the Azure OpenAI resource to collect metrics and logs in these destinations.

## Issue number

#000

## Checklist before requesting a review
- [ ] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [ ] I have executed pre-commit on my machine
- [ ] I have passed pr-check on my machine

Thanks for your cooperation!

2023-06-06 20:21 UTC, zioproto commented
@lonegunmanb please could you review this PR from our colleague @paolosalvatori ?
Please enable the E2E Tests pipeline for this PR. Thanks

2023-06-07 10:01 UTC, lonegunmanb requested changes
Thanks @paolosalvatori for opening this pr! Some review comments, and could we rename `diagnosticsetting.tf` to `diagnostic_setting.tf` to follow the snake naming convention? Thanks!

2023-06-07 10:01 UTC, lonegunmanb commented on variables.tf
> +    log_analytics_destination_type     = (Optional) Possible values are AzureDiagnostics and Dedicated. When set to Dedicated, logs sent to a Log Analytics workspace will go into resource specific ta
Please back-quote enums as:

```hcl
log_analytics_destination_type     = (Optional) Possible values are `AzureDiagnostics` and `Dedicated`. When set to `Dedicated`, logs sent to a Log Analytics workspace will go into resource specific tables, instead of the legacy AzureDiagnostics table.
```

2023-06-07 10:01 UTC, lonegunmanb commented on variables.tf
> +    retention_policy_enabled       = optional(bool, true)
It looks like we can config different retention policies for different `enabled_log`, could we use the following object?:

```hcl
audit_log_retention_policy = optional(object({
  enabled = optional(bool, true)
  days = optional(number, 30)
}))
request_response_log_retention_policy = optional(object({
  enabled = optional(bool, true)
  days = optional(number, 30)
}))
trace_log_retention_policy = optional(object({
  enabled = optional(bool, true)
  days = optional(number, 30)
}))

2023-06-07 10:01 UTC, lonegunmanb commented on diagnosticsetting.tf
> +    category = "Audit"
Should we make these `enabled_log` nested blocks `dynamic` so the user could decide whether turn them on or not? (not required if we can justify this config is essential to OpenAI service)

Is there any special reason we didn't make `category_group` configurable for `enabled_log`?

2023-06-07 10:01 UTC, lonegunmanb commented on variables.tf
> +    retention_policy_days          = optional(number, 30)
In the provider's schema `retention_policy.days` hasn't a default value, is there any special reason we use `30` here?

2023-06-07 13:12 UTC, paolosalvatori commented
> Thanks @paolosalvatori for opening this pr! Some review comments, and could we rename `diagnosticsetting.tf` to `diagnostic_setting.tf` to follow the snake naming convention? Thanks!

Sure, no worries, I usually use the snake naming convention. This time I didn't because I saw that the `privateendpoint.tf` `privateendpoint_data.tf` files is not compliant to this convention. I will change the file's name to `diagnostic_setting.tf`. May I suggest doing the same thing for the `privateendpoint.tf` and `privateendpoint_data.`  files and renaming them to `private_endpoint.tf` and `private_endpoint_data.tf`? I changed the name of both `privateendpoint.tf` `privateendpoint_data.tf` files to follow the snake naming convention.

2023-06-07 13:13 UTC, paolosalvatori commented on variables.tf
> +    log_analytics_destination_type     = (Optional) Possible values are AzureDiagnostics and Dedicated. When set to Dedicated, logs sent to a Log Analytics workspace will go into resource specific ta
Done!

2023-06-07 13:19 UTC, paolosalvatori commented on variables.tf
> +    retention_policy_days          = optional(number, 30)
No particular reasons apart from that 30 days correspond to 1 month. We can remove the default value, but if someone enables a retention policy and misses to set days, this may result in an error. I changed the default number of days to 7, one week.

2023-06-07 13:20 UTC, paolosalvatori commented on diagnosticsetting.tf
> +    category = "Audit"
Since we decided to create separate values for retention enabled and retention days, yes, I had the same thought.

2023-06-07 14:04 UTC, paolosalvatori commented on variables.tf
> +    retention_policy_enabled       = optional(bool, true)
Done, I did the same for metric

2023-06-14 01:55 UTC, lonegunmanb commented
> Sure, no worries, I usually use the snake naming convention. This time I didn't because I saw that the `privateendpoint.tf` `privateendpoint_data.tf` files is not compliant to this convention.

Good catch, thanks @paolosalvatori !

2023-06-14 01:57 UTC, lonegunmanb commented on variables.tf
> +    retention_policy_days          = optional(number, 30)
Thanks for your justification, makes sense.

2023-06-14 02:44 UTC, lonegunmanb approved these changes
LGTM! WDYT @soferreira @zioproto ?

2023-06-14 09:10 UTC, soferreira commented
> LGTM! WDYT @soferreira @zioproto ?

LGTM :)

2023-06-14 11:16 UTC, merged